spring:
  application:
    name: zuul-gateway
server:  port: 8762
eureka:  client:    serviceUrl:
     defaultZone: http://localhost:8761/eureka/    register-with-eureka: true
    fetch-registry: true
zuul:  ignored-patterns: '*'
  routes:    user-service:
     path: /user/**
     service-id: user-service
     sensitive-headers: Cookie,Set-Cookie    
    catalogue-service:
     path: /catalogue/**
     service-id: catalogue-service
    cart-service:  
     path: /cart/**
     service-id: cart-service      