spring:
  application:
    name: catalogue-service  datasource:    url: jdbc:mysql://localhost:3306/plantify_catalogue
    username: root
    password: root
  jpa:    hibernate:      ddl-auto: update
server:  port: 8081        
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    serviceUrl:      defaultZone: http://localhost:8761/eureka/