spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://localhost:3306/plantify_cart
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update    
    
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
         
      